---
title: "Caso 3: Reconocimiento de Actividad Humana con Celulares"
author: "Sarahí Romero"
date: "14 de diciembre de 2016"
output: pdf_document
---

#Benemérita Universidad Autónoma de Puebla 
##Programación Actuarial lll
##Equipo: 

* Ayala Vargas Daniela
* Gatica Cabrera María del Carmen 
* Reynaga Gil Daniel
* Romero López Sarahí 

#Caso: Reconocimiento de Actividad Humana con Celulares

#Introducciónn

Compañíasas como Fitbit, Nike y Jawbone Up compiten para desarrollar los algoritmos máss avanzados para atraer a nuevos usuarios. Los datos de este caso provienen de los acelerómetros ubicados en celulares Samsung Galaxy S.

Una mayor descripción de la base de datos y su recopilación puede ser hallada en la siguiente liga:

http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones

El propósito de este proyecto es demostrar la habilidad para recolectar, trabajar y limpiar bases de datos. El objetivo es preparar un conjunto ordenado de información que pueda ser trabajado en análisis posteriores.

El código correr_analisis.R hace lo siguiente:

* Une los datos de test con los de training, para crear un solo conjunto de datos.

Primero, lee los archivos de test y training, a continuación une ambos elementos en un nuevo conjunto.

```xtrain<-read.table("./train/X_train.txt")
xtest<-read.table("./test/X_test.txt")
juntos <- rbind(xtrain, xtest)
rm(xtrain,xtest)
```
Remueve elementos que ya no serán de utilidad. 

* Extrae únicamente las medidas de media y desviación estándar de cada medición.

Antes que nada, carga las etiquetas de cada variable, así después de realizar esto 
nombra adecuadamente las columnas de "juntos", el anterior conjunto de datos. 

```etiquetas<-read.table("features.txt")
colnames(juntos)<-etiquetas[,2]
patron <- c("mean", "std")
njuntos<-subset(juntos, select = grepl(paste(patron, collapse = "|"), 
                                           names(juntos)))
rm(etiquetas,patron,juntos)
```
Ahora crea un vector que indicará los valores que se desean encontrar. Utiliza así grepl; función que nos permite hallar patrones. Junto con subset "juntos" (actual conjunto de datos) se reducirá únicamente a las medidas de media y desviación estándar de cada medición.

Remueve elementos que ya no serán de utilidad. 

* Coloca etiquetas apropiadas en la base de datos con nombres de variables que las describan.

```
colnames(njuntos) <- sub("mean", "Mean", colnames(njuntos))

colnames(njuntos) <- sub("std", "Std", colnames(njuntos))

colnames(njuntos) <- sub("t", "Time", colnames(njuntos))

colnames(njuntos) <- sub("f", "Frequency", colnames(njuntos))

colnames(njuntos) <- sub("BodyBody", "Body", colnames(njuntos))

colnames(njuntos) <- sub("^", "MeanOf", colnames(njuntos))

colnames(njuntos) <- sub("-", "", colnames(njuntos))
```

* Usa nombres de actividad para describir los nombres de las actividades en la base de datos.

Primero carga datos de train y test sobre la actividad, después de unirlos,
se le otorga un factor, con niveles de 1 a 6. A continuación, cambia el 
nombre de cada nivel y se agrega como una nueva columna a un conjunto de datos 
actualizado.

```acttrain<-read.table("./train/y_train.txt")
acttest<-read.table("./test/y_test.txt")
actividad<-rbind(acttrain,acttest)

rm(acttrain,acttest)

nactividad<-factor(actividad$V1,levels = c(1:6))
levels(nactividad)<-c("WALKING","WALKING UPSTAIRS","WALKING DOWNSTAIRS",
                      "SITTING","STANDING","LAYING")
njuntos2<-cbind(nactividad,njuntos)

```

* Con los datos del paso anterior, crea una segunda base de datos independiente 
con el promedio de cada variable para cada actividad y cada sujeto.

Se agrega la información de los sujetos, uniendo lo de test y training en uno solo. 
Así se vuelve a agregar como columna al conjunto de datos. 
Después se instala el paquete dplyr, que permite así obtener el promedio de cada variable 
y cada sujeto. 

```sujetostrain<-read.table("./train/subject_train.txt")
sujetostest<-read.table("./test/subject_test.txt")
sujetos<-rbind(sujetostrain,sujetostest)[,1]
njuntos3<-cbind(sujetos,njuntos2)

library(dplyr)
promedio <- njuntos3 %>% group_by(sujetos, nactividad) %>% summarise_each(funs(mean))
write.table(promedio, row.names= F,file = "ordenada.txt") 

```
Para finalizar se escribe nuestra base de datos ya limpia. 
